### ISSUE TITLE
[SPIKE] Mock Up Design

### ISSUE THREAD

**Issue by rakeshdatta** [sjsu-cmpe281/shoppingcart#1]

**Comment by anvitabathija** [comment]
![checkout_0](https://cloud.githubusercontent.com/assets/14210989/14406594/475aeb1c-fe61-11e5-8bee-519295463f70.jpg)
![checkout_items](https://cloud.githubusercontent.com/assets/14210989/14406596/4ae2d484-fe61-11e5-9423-59d9a6d0fd24.jpg)
![front](https://cloud.githubusercontent.com/assets/14210989/14406597/4df07014-fe61-11e5-86bb-75d932f8fb87.jpg)
![front_men](https://cloud.githubusercontent.com/assets/14210989/14406598/5043841e-fe61-11e5-9c73-9f4f94e3629c.jpg)
![front_women](https://cloud.githubusercontent.com/assets/14210989/14406599/52f6d724-fe61-11e5-87a6-fc3535dfe9d9.jpg)
